# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('may_2015', models.IntegerField()),
                ('april_2015', models.IntegerField()),
                ('may_2014', models.IntegerField()),
                ('MoM', models.FloatField()),
                ('YoY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthByMonth',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('actual', models.IntegerField()),
                ('forest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthView',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('desktop', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('total_2015', models.IntegerField()),
                ('total_2014', models.IntegerField()),
            ],
        ),
    ]
