# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewsPerHour',
            fields=[
                ('id', models.DateTimeField(primary_key=True, serialize=False)),
                ('page_views', models.IntegerField()),
            ],
        ),
    ]
