# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_pageviewsperhour'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoViews',
            fields=[
                ('id', models.DateTimeField(primary_key=True, serialize=False)),
                ('video_views', models.IntegerField()),
            ],
        ),
    ]
