# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_videoviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPerChannel',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('Other', models.IntegerField()),
                ('Direct', models.IntegerField()),
                ('Email', models.IntegerField()),
                ('Organic_Search', models.IntegerField()),
                ('Paid_Search', models.IntegerField()),
                ('Referral', models.IntegerField()),
                ('Socail', models.IntegerField()),
            ],
        ),
    ]
