# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_auto_20160707_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Title', models.CharField(max_length=200)),
                ('Engaged_time', models.IntegerField()),
                ('Page_views', models.IntegerField()),
                ('Path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='toppages',
            unique_together=set([('Date', 'Title')]),
        ),
    ]
