# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_auto_20160714_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppages',
            old_name='Page_views',
            new_name='Unique_users',
        ),
    ]
