# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_auto_20160714_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPerChannel',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('Other', models.IntegerField()),
                ('Direct', models.IntegerField()),
                ('Email', models.IntegerField()),
                ('Organic_Search', models.IntegerField()),
                ('Paid_Search', models.IntegerField()),
                ('Referral', models.IntegerField()),
                ('Social', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='MonthByMonth',
        ),
        migrations.DeleteModel(
            name='MonthView',
        ),
        migrations.DeleteModel(
            name='PageViewsPerHour',
        ),
        migrations.DeleteModel(
            name='UsersPerChannelAndBrand',
        ),
        migrations.DeleteModel(
            name='VideoViews',
        ),
        migrations.AlterUniqueTogether(
            name='toppages',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='toppages',
            index_together=set([('Date', 'Title')]),
        ),
    ]
