# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_auto_20160714_1602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toppages',
            unique_together=set([('Date', 'Title')]),
        ),
        migrations.AlterIndexTogether(
            name='toppages',
            index_together=set([]),
        ),
    ]
