# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_auto_20160714_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top4Posts',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('pic', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('viral_unique', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
