# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0012_auto_20160718_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPosts_MH',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('viral_unique', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Top4Posts',
        ),
    ]
