# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_auto_20160724_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPosts_BI',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('viral_unique', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TopPosts_PVN',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('viral_unique', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TopPosts_ROL',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('viral_unique', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TopPosts_RW',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('viral_unique', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TopPosts_WE',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('viral_unique', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TopPosts_WH',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('viral_unique', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
            ],
        ),
    ]
