# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0015_users_bi_users_mh_users_pvn_users_rol_users_rw_users_we_users_wh'),
    ]

    operations = [
        migrations.AddField(
            model_name='topposts_bi',
            name='unique',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topposts_mh',
            name='unique',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topposts_pvn',
            name='unique',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topposts_rol',
            name='unique',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topposts_rw',
            name='unique',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topposts_we',
            name='unique',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topposts_wh',
            name='unique',
            field=models.IntegerField(default=1),
        ),
    ]
