# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0016_auto_20160727_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topposts_bi',
            name='unique',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='topposts_mh',
            name='unique',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='topposts_pvn',
            name='unique',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='topposts_rol',
            name='unique',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='topposts_rw',
            name='unique',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='topposts_we',
            name='unique',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='topposts_wh',
            name='unique',
            field=models.IntegerField(default=1000000),
        ),
    ]
